/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Principal;

import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Antonio Borja
 */
public class ValidacionesReservasCampos extends javax.swing.JFrame {

    /**
     * Creates new form ValidacionesReservasCampos
     */
    public ValidacionesReservasCampos() {
        initComponents();
        Clases.Validaciones v = new Clases.Validaciones();
        this.setLocationRelativeTo(this);

        int anoActual = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
        for (int ano = 2023; ano >= 1900; ano--) {
            anoFabricacionComboBox.addItem(Integer.toString(ano));
        }

        String[] tiposVehiculo = {"Sedán", "SUV", "Camioneta", "Deportivo", "Pick-up", "Furgoneta"};
        for (String tipo : tiposVehiculo) {
            tipoVehiculoComboBox.addItem(tipo);
        }

        String[] colores = {"Rojo", "Azul", "Blanco", "Negro", "Plateado", "Verde", "Amarillo", "Gris", "Otro"};
        for (String color : colores) {
            colorComboBox.addItem(color);
        }

        String[] transmisiones = {"Automática", "Manual"};
        for (String transmision : transmisiones) {
            transmisionComboBox.addItem(transmision);
        }
        String[] opcionesDisponibilidad = {"Disponible", "No Disponible"};
        for (String opcion : opcionesDisponibilidad) {
            disponibilidadComboBox.addItem(opcion);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        marcaTextField = new javax.swing.JTextField();
        modeloTextField = new javax.swing.JTextField();
        anoFabricacionComboBox = new javax.swing.JComboBox<>();
        tipoVehiculoComboBox = new javax.swing.JComboBox<>();
        colorComboBox = new javax.swing.JComboBox<>();
        transmisionComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_Crear = new javax.swing.JButton();
        disponibilidadComboBox = new javax.swing.JComboBox<>();
        imagenLabel = new javax.swing.JLabel();
        txtPrecioxHora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(555, 625));
        setMinimumSize(new java.awt.Dimension(555, 625));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.setBorder(new javax.swing.border.MatteBorder(null));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 705));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(marcaTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 350, -1));
        jPanel1.add(modeloTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 350, -1));

        jPanel1.add(anoFabricacionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 350, -1));

        jPanel1.add(tipoVehiculoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 350, -1));

        jPanel1.add(colorComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 350, -1));

        jPanel1.add(transmisionComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 350, -1));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Marca");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Año de Fabricación");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Tipo de Vehículo");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Color");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Transmisión");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Disponibilidad");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Imagen");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        btn_Crear.setText("Crear");
        btn_Crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CrearActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 500, 250, 40));

        jPanel1.add(disponibilidadComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 350, -1));

        imagenLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        imagenLabel.setForeground(new java.awt.Color(255, 255, 255));
        imagenLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imagenLabel.setText("Agregar Imagen");
        imagenLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        imagenLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        imagenLabel.setMaximumSize(new java.awt.Dimension(250, 149));
        imagenLabel.setMinimumSize(new java.awt.Dimension(250, 149));
        imagenLabel.setPreferredSize(new java.awt.Dimension(250, 149));
        imagenLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imagenLabelMouseClicked(evt);
            }
        });
        jPanel1.add(imagenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 250, 149));

        txtPrecioxHora.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtPrecioxHoraFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtPrecioxHoraFocusLost(evt);
            }
        });
        txtPrecioxHora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtPrecioxHoraKeyTyped(evt);
            }
        });
        jPanel1.add(txtPrecioxHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 350, -1));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Precio por hora");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Registro de Vehiculos");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CrearActionPerformed
        String marca = marcaTextField.getText().trim();
        String modelo = modeloTextField.getText().trim();
        String precioPorHora = txtPrecioxHora.getText().trim();
        
        if (marca.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de Marca no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (modelo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de Modelo no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        } else if (precioPorHora.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El campo de Precio por Hora no puede estar vacío.", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            if (imagenLabel.getIcon() == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar una imagen.", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(null, "Registro Guardado exitosamente");
            }
        }
    }//GEN-LAST:event_btn_CrearActionPerformed

    private void imagenLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imagenLabelMouseClicked
        imagenLabel.setText("");

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileFilter(new FileNameExtensionFilter("Archivos de imagen", "jpg", "png", "jpeg", "gif"));

        int seleccion = fileChooser.showOpenDialog(this);
        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivoImagen = fileChooser.getSelectedFile();
            try {
                BufferedImage imagen = ImageIO.read(archivoImagen);
                ImageIcon icono = new ImageIcon(imagen);
                imagenLabel.setIcon(icono);
            } catch (IOException e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Error al cargar la imagen.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_imagenLabelMouseClicked

    private void txtPrecioxHoraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioxHoraKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        
        // Permitir teclas de control como Backspace y Delete
        if (Character.isISOControl(c)) {
            return;
        }
    
        if(c == '.' && txtPrecioxHora.getText().isEmpty()){
            evt.consume();
            return;
        }

        // Asegurarse de que solo se ingresen dígitos o un único punto decimal
        if (!Character.isDigit(c) && c != '.') {
            evt.consume();
        }

        // Asegurarse de que solo haya un punto decimal
        if (c == '.' && txtPrecioxHora.getText().contains(".")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtPrecioxHoraKeyTyped

    private void txtPrecioxHoraFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioxHoraFocusLost
        String texto = txtPrecioxHora.getText().trim();
        if (!texto.isEmpty() && !texto.startsWith("$")) {
            txtPrecioxHora.setText("$" + texto);
        }
    }//GEN-LAST:event_txtPrecioxHoraFocusLost

    private void txtPrecioxHoraFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtPrecioxHoraFocusGained
        String texto = txtPrecioxHora.getText().trim();
        if (!texto.startsWith("$")) {
            txtPrecioxHora.setText("$" + texto);
        }
    }//GEN-LAST:event_txtPrecioxHoraFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ValidacionesReservasCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ValidacionesReservasCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ValidacionesReservasCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ValidacionesReservasCampos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ValidacionesReservasCampos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> anoFabricacionComboBox;
    private javax.swing.JButton btn_Crear;
    private javax.swing.JComboBox<String> colorComboBox;
    private javax.swing.JComboBox<String> disponibilidadComboBox;
    private javax.swing.JLabel imagenLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField marcaTextField;
    private javax.swing.JTextField modeloTextField;
    private javax.swing.JComboBox<String> tipoVehiculoComboBox;
    private javax.swing.JComboBox<String> transmisionComboBox;
    private javax.swing.JTextField txtPrecioxHora;
    // End of variables declaration//GEN-END:variables
}
